<?php

namespace AppBundle\Repository;

/**
 * CountryV0Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryV0Repository extends \Doctrine\ORM\EntityRepository
{
}
