<?php

namespace AppBundle\Repository;

/**
 * DrugFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrugFormRepository extends \Doctrine\ORM\EntityRepository
{
}
