<?php

namespace AppBundle\Repository;

/**
 * DrugPdfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrugPdfRepository extends \Doctrine\ORM\EntityRepository
{
}
