<?php

namespace AppBundle\Repository;

/**
 * DrugAlternateNameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrugAlternateNameRepository extends \Doctrine\ORM\EntityRepository
{
}
