<?php

namespace AppBundle\Repository;

/**
 * DrugTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DrugTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
