<?php

namespace AppBundle\Repository;

/**
 * IngredientCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
