<?php

namespace AppBundle\Repository;

/**
 * IngredientV0Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IngredientV0Repository extends \Doctrine\ORM\EntityRepository
{
}
