<?php

namespace AppBundle\Repository;

/**
 * InteractionCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractionCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
