<?php

namespace AppBundle\Repository;

/**
 * InteractionSeverityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InteractionSeverityRepository extends \Doctrine\ORM\EntityRepository
{
}
