<?php

namespace AppBundle\Repository;

/**
 * ManufacturerTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManufacturerTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
