<?php

namespace AppBundle\Repository;

/**
 * MedicineIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MedicineIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
