<?php

namespace AppBundle\Repository;

/**
 * ReminderAlarmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReminderAlarmRepository extends \Doctrine\ORM\EntityRepository
{
}
