<?php

namespace AppBundle\Repository;

/**
 * WadaIngredientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WadaIngredientRepository extends \Doctrine\ORM\EntityRepository
{
}
