NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

rest:
    resource: "@RestBundle/Resources/config/routing.yml"
    prefix:   /rest

app_home:
    path:     /
    defaults: { _controller: AppBundle:Default:index }

app_registration:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

app_need_confirmation:
    path:     /confirm/{id}
    defaults: { _controller: AppBundle:Registration:needConfirm }
    requirements:
        id: '\d+'

app_confirmation:
    path:     /confirmation/{id}/{sign}
    defaults: { _controller: AppBundle:Registration:Confirmation }
    requirements:
        id: '\d+'

app_congratulation:
    path:     /congratulation
    defaults: { _controller: AppBundle:Default:congratulation }

app_login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

app_logout:
    path:     /logout
    defaults: { _controller: AppBundle:Security:logout }
