# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        entity:
            entity:
                class: AppBundle:User
                property: username

        xtoken:
            entity:
                class: RestBundle:Token
                property: token

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        rest:
            pattern: ^/rest/(?!(register|login|resetPassword|logout))
            guard:
                authenticators:
                    - rest.rest_token_authenticator
            provider: xtoken

        main:
            anonymous: ~
            pattern: ^/
            form_login:
                login_path: app_login
                check_path: app_login
                username_parameter: "email"
                password_parameter: "password"
            provider: entity

    encoders:
        AppBundle\Entity\User: bcrypt
